from __future__ import annotations

import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

SCRIPT = Path(__file__).resolve().parents[1] / "scripts" / "sync_vendor.py"

UPSTREAM_SKILL = """---
name: demo
description: "Drive the app."
---

Write `.cursor/skills/verify-<app>/SKILL.md` and open one PR of fixes.
"""


class VendorSyncTests(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = tempfile.TemporaryDirectory()
        base = Path(self.tmp.name)
        self.root = base / "repo"
        self.source = base / "upstream"
        (self.source / "pack" / "skills" / "demo").mkdir(parents=True)
        (self.source / "pack" / "skills" / "demo" / "SKILL.md").write_text(UPSTREAM_SKILL, encoding="utf-8")
        (self.source / "pack" / "LICENSE").write_text("MIT License\nCopyright (c) Upstream\n", encoding="utf-8")
        (self.root / "vendor" / "pack").mkdir(parents=True)
        self.write_config(
            [
                {"file": "demo/SKILL.md", "old": ".cursor/skills/", "new": ".agents/skills/"},
                {"file": "demo/SKILL.md", "old": "open one PR of fixes", "new": "make one local commit of fixes"},
            ]
        )

    def tearDown(self) -> None:
        self.tmp.cleanup()

    def write_config(self, patches: list[dict]) -> None:
        cfg = {
            "repo": "https://example.invalid/upstream",
            "pinned": "old-sha",
            "license": "pack/LICENSE",
            "skills": {"demo": "pack/skills/demo"},
            "patches": patches,
            "forbid": [".cursor/", " PR "],
        }
        (self.root / "vendor" / "pack" / "sync.json").write_text(json.dumps(cfg), encoding="utf-8")

    def run_update(self) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            [sys.executable, str(SCRIPT), "--root", str(self.root), "update", "pack",
             "--source", str(self.source), "--ref", "new-sha-0123456789"],
            text=True, capture_output=True,
        )

    def pinned(self) -> str:
        return json.loads((self.root / "vendor" / "pack" / "sync.json").read_text(encoding="utf-8"))["pinned"]

    def test_update_writes_patched_skill_license_and_pin(self) -> None:
        result = self.run_update()
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(
            (self.root / "demo" / "SKILL.md").read_text(encoding="utf-8"),
            "---\n# Generated by scripts/sync_vendor.py from https://example.invalid/upstream@new-sha-0123;"
            " edit vendor/*/sync.json, not this file.\nname: demo\ndescription: \"Drive the app.\"\n---\n\n"
            "Write `.agents/skills/verify-<app>/SKILL.md` and make one local commit of fixes.\n",
        )
        self.assertEqual((self.root / "demo" / "LICENSE").read_text(encoding="utf-8"), "MIT License\nCopyright (c) Upstream\n")
        self.assertEqual(self.pinned(), "new-sha-0123456789")

    def test_patch_that_no_longer_applies_aborts_without_writing(self) -> None:
        self.write_config([{"file": "demo/SKILL.md", "old": "text upstream removed", "new": "x"}])
        result = self.run_update()
        self.assertEqual(result.returncode, 1)
        self.assertIn("patch no longer applies to demo/SKILL.md", result.stderr)
        self.assertFalse((self.root / "demo").exists())
        self.assertEqual(self.pinned(), "old-sha")

    def test_forbidden_leftover_aborts_and_keeps_previous_output(self) -> None:
        (self.root / "demo").mkdir()
        (self.root / "demo" / "SKILL.md").write_text("previous build\n", encoding="utf-8")
        self.write_config([{"file": "demo/SKILL.md", "old": ".cursor/skills/", "new": ".agents/skills/"}])
        result = self.run_update()
        self.assertEqual(result.returncode, 1)
        self.assertIn("still contains ' PR '", result.stderr)
        self.assertEqual((self.root / "demo" / "SKILL.md").read_text(encoding="utf-8"), "previous build\n")
        self.assertEqual(self.pinned(), "old-sha")


if __name__ == "__main__":
    unittest.main()
