#!/usr/bin/env python3
"""Repository-local documentation governance verifier.

Generated by dsh-doc-audits {{SKILL_VERSION}}. Uses only Python's standard library.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from fnmatch import fnmatchcase
from pathlib import Path
from urllib.parse import unquote


def matches(path: str, pattern: str) -> bool:
    path = path.replace(os.sep, "/").lstrip("./")
    pattern = pattern.replace(os.sep, "/").lstrip("./")
    if pattern.endswith("/**"):
        prefix = pattern[:-3].rstrip("/")
        return path == prefix or path.startswith(prefix + "/")
    return fnmatchcase(path, pattern)


DEFAULT_EXCLUDE_PATTERNS = (
    ".git/**",
    ".venv/**",
    "node_modules/**",
    "**/__pycache__/**",
)


def files(root: Path, exclude_patterns=()) -> list[str]:
    patterns = (*DEFAULT_EXCLUDE_PATTERNS, *(str(pattern) for pattern in exclude_patterns))
    result = []
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        rel = path.relative_to(root).as_posix()
        if any(matches(rel, pattern) for pattern in patterns):
            continue
        result.append(rel)
    return sorted(result)


def finding(code: str, severity: str, path: str, message: str, **extra):
    value = {"code": code, "severity": severity, "path": path, "message": message}
    value.update(extra)
    return value


def load_manifest(root: Path):
    path = root / "docs" / "governance.yaml"
    if not path.is_file():
        return None, [finding("governance-missing", "error", "docs/governance.yaml", "Governance manifest is missing.")]
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        return None, [finding("governance-invalid", "error", "docs/governance.yaml", str(exc))]
    if not isinstance(data, dict):
        return None, [finding(
            "governance-invalid",
            "error",
            "docs/governance.yaml",
            "Governance manifest root must be an object.",
        )]
    return data, []


def link_findings(root: Path, exclude_patterns=()):
    result = []
    regex = re.compile(r"!?\[[^\]]*\]\(([^)]+)\)")
    scheme = re.compile(r"^[A-Za-z][A-Za-z0-9+.-]*:")
    for rel in files(root, exclude_patterns):
        if not rel.endswith(".md"):
            continue
        path = root / rel
        for line_no, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            for raw in regex.findall(line):
                target = raw.strip()
                if target.startswith("<") and ">" in target:
                    target = target[1:target.index(">")]
                else:
                    target = target.split(maxsplit=1)[0]
                if not target or target.startswith(('#', '/')) or scheme.match(target):
                    continue
                target = unquote(target.split('#', 1)[0].split('?', 1)[0])
                if not target:
                    continue
                resolved = (path.parent / target).resolve()
                try:
                    resolved.relative_to(root)
                except ValueError:
                    result.append(finding("markdown-link-outside", "error", rel, f"Line {line_no}: {raw}"))
                    continue
                if not resolved.exists():
                    result.append(finding("markdown-link-broken", "error", rel, f"Line {line_no}: {raw}"))
    return result


def current_markdown_files(root: Path, config, exclude_patterns=()):
    current = config.get("tiers", {}).get("current", [])
    return [
        root / rel
        for rel in files(root, exclude_patterns)
        if rel.endswith(".md") and any(matches(rel, pattern) for pattern in current)
    ]


def audit_findings(root: Path, config, exclude_patterns=()):
    result = []
    audit = config.get("audit", {})
    minimum = int(audit.get("duplicate_min_chars", 180))
    occurrences = {}
    current_files = current_markdown_files(root, config, exclude_patterns)
    for path in current_files:
        rel = path.relative_to(root).as_posix()
        text = path.read_text(encoding="utf-8")
        for paragraph in re.split(r"\n\s*\n", text):
            normalized = " ".join(paragraph.split())
            if len(normalized) < minimum or normalized.startswith("#") or normalized.startswith("```"):
                continue
            occurrences.setdefault(normalized, []).append(rel)
    for paragraph, paths in sorted(occurrences.items()):
        unique_paths = sorted(set(paths))
        if len(unique_paths) > 1:
            result.append(finding(
                "duplicate-prose",
                "warning",
                unique_paths[0],
                "A long prose block is duplicated across current documentation owners.",
                paths=unique_paths,
                excerpt=paragraph[:160],
            ))

    historical = config.get("tiers", {}).get("historical", [])
    prefixes = sorted({pattern[:-3].rstrip("/") if pattern.endswith("/**") else pattern for pattern in historical})
    terms = [str(term).lower() for term in audit.get("historical_authority_terms", [])]
    for path in current_files:
        rel = path.relative_to(root).as_posix()
        for line_no, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            lowered = line.lower()
            if terms and any(term in lowered for term in terms) and any(prefix in line for prefix in prefixes):
                result.append(finding(
                    "historical-authority-leak",
                    "warning",
                    rel,
                    f"Line {line_no} names a historical tier as current authority.",
                    line=line_no,
                ))
    return result


def note_findings(root: Path, config):
    result = []
    note_config = config.get("agent_notes", {})
    note_root = root / note_config.get("root", ".agents/notes")
    statuses = note_config.get("statuses", {})
    required = {
        "proposed": {"Problem", "Proposal", "Alternatives considered", "Acceptance criteria", "Risks"},
        "implemented": {"Problem", "Decision", "Alternatives considered", "Consequences"},
        "rejected": {"Problem", "Proposal", "Alternatives considered"},
        "archived": {"Problem", "Decision", "Alternatives considered", "Consequences"},
    }
    forbidden = {"Proposal", "Plan", "Migration plan", "Acceptance criteria"}
    if not note_root.exists():
        return result
    for lifecycle, expected in statuses.items():
        folder = note_root / lifecycle
        if not folder.exists():
            continue
        for path in folder.rglob("*.md"):
            if path.name in {"README.md", "_template.md"} or path.name.endswith(".zh.md"):
                continue
            rel = path.relative_to(root).as_posix()
            text = path.read_text(encoding="utf-8")
            status_match = re.search(r"(?m)^Status:\s*(.+?)\s*$", text)
            actual = status_match.group(1) if status_match else ""
            ok = actual == expected
            if lifecycle == "rejected":
                ok = actual == "rejected" or actual.startswith("rejected —") or actual.startswith("rejected -")
            if not ok:
                result.append(finding("agent-note-status-mismatch", "error", rel, f"Expected {expected!r}, found {actual!r}."))
            headings = set(re.findall(r"(?m)^##\s+(.+?)\s*$", text))
            for heading in sorted(required.get(lifecycle, set()) - headings):
                result.append(finding("agent-note-required-heading-missing", "error", rel, heading))
            if lifecycle in {"implemented", "archived"}:
                for heading in sorted(headings & forbidden):
                    result.append(finding("agent-note-forbidden-heading", "error", rel, heading))
    return result


def verify(root: Path, base: str | None = None):
    config, result = load_manifest(root)
    if config is None:
        return {"ok": False, "findings": result}
    for name, rel in config.get("authority", {}).items():
        if rel and not (root / rel).exists():
            result.append(finding("authority-missing", "error", rel, f"Missing authority {name}."))
    exclude_patterns = config.get("exclude", [])
    all_files = files(root, exclude_patterns)
    current = config.get("tiers", {}).get("current", [])
    historical = config.get("tiers", {}).get("historical", [])
    for rel in all_files:
        if any(matches(rel, p) for p in current) and any(matches(rel, p) for p in historical):
            result.append(finding("tier-overlap", "error", rel, "File is both current and historical."))
    result.extend(link_findings(root, exclude_patterns))
    result.extend(note_findings(root, config))
    result.extend(audit_findings(root, config, exclude_patterns))
    for rel, rule in config.get("budgets", {}).items():
        path = root / rel
        if path.is_file() and rule.get("metric") == "unicode_chars":
            count = len(path.read_text(encoding="utf-8"))
            maximum = rule.get("max")
            if isinstance(maximum, int) and count > maximum:
                result.append(finding("document-budget-exceeded", "error", rel, f"{count} > {maximum}"))
    changed = []
    if base:
        try:
            completed = subprocess.run(["git", "-C", str(root), "diff", "--name-only", f"{base}...HEAD"], check=True, text=True, capture_output=True)
            changed = sorted(line for line in completed.stdout.splitlines() if line)
        except (OSError, subprocess.CalledProcessError) as exc:
            result.append(finding("git-diff-failed", "error", ".", str(exc)))
        for mapping in config.get("impact_mappings", []):
            code_changed = [p for p in changed if any(matches(p, q) for q in mapping.get("code", []))]
            docs_changed = [p for p in changed if any(matches(p, q) for q in mapping.get("docs", []))]
            if code_changed and not docs_changed:
                level = mapping.get("level", "soft")
                result.append(finding(
                    "hard-doc-impact-missing" if level == "hard" else "soft-doc-impact-unreviewed",
                    "error" if level == "hard" else "warning",
                    mapping.get("name", "unnamed"),
                    "Mapped code changed without owning documentation.",
                    changed_code=code_changed,
                    expected_docs=mapping.get("docs", []),
                ))
    result.sort(key=lambda item: (item["severity"], item["code"], item["path"]))
    return {
        "ok": not any(item["severity"] == "error" for item in result),
        "changed_files": changed,
        "findings": result,
        "summary": {
            "errors": sum(item["severity"] == "error" for item in result),
            "warnings": sum(item["severity"] != "error" for item in result),
        },
    }


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", default=".")
    parser.add_argument("--base")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args(argv)
    root = Path(args.repo).expanduser().resolve()
    payload = verify(root, args.base)
    if args.json:
        print(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True))
    else:
        print("PASS" if payload["ok"] else "FAIL")
        for item in payload["findings"]:
            print(f"{item['severity'].upper()} {item['code']} {item['path']}: {item['message']}")
    return 0 if payload["ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
