#!/usr/bin/env python3
"""Generated by dsh-doc-audits {{SKILL_VERSION}}; do not edit directly.
Source: dsh-doc-audits/scripts/repo_docs.py; generator: scripts/generate_verifier.py.
"""
from __future__ import annotations

import argparse

import json

import html

from html.parser import HTMLParser

import unicodedata

import os

import re

import subprocess

import sys

from fnmatch import fnmatchcase

from urllib.parse import unquote

from datetime import date

from pathlib import Path

from typing import Any, Iterable

DEFAULT_EXCLUDE_PATTERNS = (
    ".git/**",
    ".dsh-doc-audits/**",
    ".venv/**",
    "node_modules/**",
    "**/__pycache__/**",
)

STRUCTURE_ONLY_ASSURANCE = (
    "structure-only: a pass proves manifest, link, lifecycle, budget and readiness conditions, "
    "not that any document agrees with the code; semantic review and fresh-session assessment remain required"
)

def _normalize_repo(repo: str | os.PathLike[str] | Path) -> Path:
    path = Path(repo).expanduser().resolve()
    if not path.exists():
        raise FileNotFoundError(f"repository path does not exist: {path}")
    if not path.is_dir():
        raise NotADirectoryError(f"repository path is not a directory: {path}")
    return path

def _git_worktree_files(repo: Path) -> set[str] | None:
    """Tracked plus untracked non-ignored paths, as snapshot() sees them; None unless repo is a Git worktree root."""
    # An inherited Git environment must not retarget reads to another checkout.
    env = {key: value for key, value in os.environ.items()
           if key not in {"GIT_DIR", "GIT_WORK_TREE", "GIT_INDEX_FILE", "GIT_COMMON_DIR"}}
    try:
        top = subprocess.run(["git", "-C", str(repo), "rev-parse", "--show-toplevel"],
                             capture_output=True, env=env, timeout=30)
        if top.returncode or Path(os.fsdecode(top.stdout.strip())).resolve() != repo.resolve():
            return None
        listed = subprocess.run(["git", "-C", str(repo), "ls-files", "-z", "--cached", "--others", "--exclude-standard"],
                                capture_output=True, env=env, timeout=30, check=True)
    except (OSError, subprocess.SubprocessError):
        return None
    return {os.fsdecode(name) for name in listed.stdout.split(b"\0") if name}

def _relative_files(repo: Path, exclude_patterns: Iterable[str] = ()) -> list[str]:
    """Files Git shows at a worktree root; elsewhere every file under repo."""
    patterns = (*DEFAULT_EXCLUDE_PATTERNS, *(str(pattern) for pattern in exclude_patterns))
    listed = _git_worktree_files(repo)
    if listed is None:
        listed = [path.relative_to(repo).as_posix() for path in repo.rglob("*")]
    return sorted(
        rel
        for rel in listed
        if (repo / rel).is_file() and not any(_matches(rel, pattern) for pattern in patterns)
    )

def _glossary_paths(config: dict[str, Any]) -> list[str]:
    """One explicit Markdown owner, or both conventional candidates; never infer authority."""
    authority = config.get("authority", {})
    if not isinstance(authority, dict):
        raise ValueError("authority must be an object")
    if "glossary" not in authority:
        return ["GLOSSARY.md", "CONTEXT.md"]
    value = authority["glossary"]
    if (not isinstance(value, str) or not value.endswith(".md")
            or value.startswith(("/", "~")) or "\\" in value or ":" in value
            or any(ord(c) < 32 for c in value) or any(c in value for c in "*?[]")
            or any(part in {"", ".", "..", ".git", ".github", ".dsh-doc-audits"} for part in value.split("/"))):
        raise ValueError("authority.glossary must be a canonical relative Markdown file path outside Git/control metadata")
    return [value]

def _finding(code: str, severity: str, path: str, message: str, **extra: Any) -> dict[str, Any]:
    value: dict[str, Any] = {
        "code": code,
        "severity": severity,
        "path": path,
        "message": message,
    }
    value.update(extra)
    return value

def _matches(path: str, pattern: str) -> bool:
    normalized = path.replace(os.sep, "/").lstrip("./")
    pattern = pattern.replace(os.sep, "/").lstrip("./")
    if pattern.endswith("/**"):
        prefix = pattern[:-3].rstrip("/")
        return normalized == prefix or normalized.startswith(prefix + "/")
    return fnmatchcase(normalized, pattern)

def _manifest_issues(data: Any) -> list[str]:
    """Validate the public manifest contract, including nested types, before use."""
    issues: list[str] = []
    if not isinstance(data, dict):
        return ["root must be an object"]
    required = {"schema_version", "authority", "tiers", "agent_notes", "budgets", "impact_mappings", "audit"}
    issues.extend(f"missing field: {name}" for name in sorted(required - data.keys()))
    if data.get("schema_version") != 1 or isinstance(data.get("schema_version"), bool):
        issues.append("schema_version must be 1")
    def strings(value: Any) -> bool:
        return isinstance(value, list) and all(isinstance(x, str) and bool(x.strip()) for x in value)
    def relative(value: Any, pattern: bool = False) -> bool:
        return (isinstance(value, str) and bool(value) and not value.startswith(("/", "~"))
                and "\\" not in value and ":" not in value and ".." not in value.split("/")
                and not any(ord(c) < 32 for c in value)
                and (pattern or not any(c in value for c in "*?[]")))
    authority = data.get("authority")
    if not isinstance(authority, dict) or not authority or not all(relative(v) for v in authority.values()):
        issues.append("authority must be a nonempty map of names to relative file paths")
    try:
        _glossary_paths(data)
    except ValueError as exc:
        issues.append(str(exc))
    tiers = data.get("tiers")
    if not isinstance(tiers, dict) or not strings(tiers.get("current")) or not strings(tiers.get("historical")):
        issues.append("tiers must contain current and historical string arrays")
    elif any(not strings(arr) for arr in tiers.values()) or not tiers["current"] or not all(relative(v, True) for arr in tiers.values() for v in arr):
        issues.append("tiers require relative patterns and a nonempty current tier")
    notes = data.get("agent_notes")
    expected = {"proposed": "proposed", "implemented": "implemented", "rejected": "rejected", "archived": "implemented"}
    if not isinstance(notes, dict) or not relative(notes.get("root")) or notes.get("statuses") != expected:
        issues.append("agent_notes requires a relative root and the four lifecycle/status pairs")
    budgets = data.get("budgets")
    if not isinstance(budgets, dict):
        issues.append("budgets must be an object")
    else:
        for path, rule in budgets.items():
            if (not relative(path) or not isinstance(rule, dict) or rule.get("metric") != "unicode_chars"
                    or type(rule.get("max")) is not int or rule["max"] < 1):
                issues.append(f"invalid budget: {path}")
    mappings = data.get("impact_mappings")
    if not isinstance(mappings, list):
        issues.append("impact_mappings must be an array")
    else:
        names = set()
        for item in mappings:
            if (not isinstance(item, dict) or not isinstance(item.get("name"), str) or not item["name"]
                    or not strings(item.get("code")) or not item["code"]
                    or not strings(item.get("docs")) or not item["docs"]
                    or item.get("level") not in {"hard", "soft"}
                    or not isinstance(item.get("code_repository", "local"), str)
                    or item.get("code_repository", "local") not in {"local", "external"}):
                issues.append("each impact mapping requires name, code, docs, hard/soft level and local/external code_repository")
            elif item["name"] in names or not all(relative(v, True) for v in item["code"] + item["docs"]):
                issues.append("impact mappings require unique names and relative patterns")
            else:
                names.add(item["name"])
    audit = data.get("audit")
    if (not isinstance(audit, dict) or type(audit.get("duplicate_min_chars")) is not int
            or audit["duplicate_min_chars"] < 1 or not strings(audit.get("historical_authority_terms"))):
        issues.append("audit requires a positive duplicate_min_chars and historical_authority_terms array")
    if "exclude" in data and (not strings(data["exclude"]) or not all(relative(v, True) for v in data["exclude"])):
        issues.append("exclude must contain relative patterns")
    return issues

def _readiness_findings(root: Path, config: dict[str, Any], completion: bool = False) -> list[dict[str, Any]]:
    """Scaffolding is allowed during bootstrap; never certify it as migrated."""
    findings: list[dict[str, Any]] = []
    prompts = re.compile(r"^(?:TODO|TBD|FIXME)(?:\b|[:：])|^\{\{[^}]+\}\}|"
                         r"^(?:Describe|Record|Summarize|Name|State|Link|Document|List)\b.*(?:here\b|owning path|dependency order|a maintainer must|durable stores|capabilities may|environments and deployment)", re.I)
    authority_paths = set(config.get("authority", {}).values())
    for path in _current_markdown_files(root, config):
        if path.name == "_template.md":
            continue
        rel = path.relative_to(root).as_posix()
        text = path.read_text(encoding="utf-8")
        scaffold = re.search(r"(?mi)^Status:\s*scaffold\s*$", text) is not None
        if scaffold:
            findings.append(_finding("documentation-scaffold", "error" if completion else "warning", rel,
                                     "Scaffold is not current authority; semantic authoring is pending."))
            continue
        fenced = False
        prose = []
        for line_no, line in enumerate(text.splitlines(), 1):
            stripped = line.strip()
            if stripped.startswith(("```", "~~~")):
                fenced = not fenced
                continue
            if fenced or not stripped or stripped.startswith(("#", ">", "<!--", "Status:", "Last reviewed:", "Owner paths:")):
                continue
            prose.append(stripped)
            if prompts.search(re.sub(r"^(?:[-*+] |[0-9]+[.)] )", "", stripped)):
                findings.append(_finding("current-authority-placeholder", "error", rel,
                                         "Current documentation contains an unfinished authoring prompt.", line=line_no))
        if completion and (rel in authority_paths or re.search(r"(?mi)^Status:\s*current authority", text)) and not prose:
            findings.append(_finding("current-authority-empty", "error", rel, "Current owner has no substantive content."))
    return findings

def _load_governance(root: Path) -> tuple[dict[str, Any] | None, list[dict[str, Any]]]:
    path = root / "docs" / "governance.yaml"
    if not path.is_file():
        return None, [_finding(
            "governance-missing",
            "error",
            "docs/governance.yaml",
            "The repository has no governance manifest.",
        )]
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        return None, [_finding(
            "governance-invalid",
            "error",
            "docs/governance.yaml",
            f"The governance manifest must be JSON-compatible YAML: {exc}",
        )]
    if not isinstance(data, dict):
        return None, [_finding(
            "governance-invalid",
            "error",
            "docs/governance.yaml",
            "The governance manifest root must be an object.",
        )]
    issues = _manifest_issues(data)
    if issues:
        return None, [_finding("governance-invalid", "error", "docs/governance.yaml", issue) for issue in issues]
    return data, []

def _markdown_prose_lines(text: str, *, preserve_inline: bool = False) -> Iterable[tuple[int, str]]:
    """Yield numbered lines outside fenced code blocks, with inline code spans blanked.

    A line-based CommonMark subset: an opening fence may follow indentation, blockquote or
    list markers; only its own character repeated at least as often, alone on a line,
    closes it. An unclosed fence runs to the end of the file.
    """
    opener_re = re.compile(r"(?:[ \t]*(?:>|[-*+][ \t]|\d{1,9}[.)][ \t]))*[ \t]*(`{3,}|~{3,})(.*)")
    code_span_re = re.compile(r"(?<![`\\])(`+)(?!`).+?(?<!`)\1(?!`)")
    fence = ""
    for line_no, line in enumerate(text.splitlines(), start=1):
        if fence:
            marker = line.lstrip(" \t>").rstrip()
            if len(marker) >= len(fence) and marker == fence[0] * len(marker):
                fence = ""
            continue
        opener = opener_re.match(line)
        # A backtick fence's info string cannot contain backticks; such a line is inline code.
        if opener and not (opener.group(1)[0] == "`" and "`" in opener.group(2)):
            fence = opener.group(1)
            continue
        yield line_no, line if preserve_inline else code_span_re.sub(lambda span: " " * len(span.group(0)), line)

def _markdown_anchors(text: str) -> set[str]:
    """Bounded GitHub-style ATX/Setext headings and explicit HTML anchors."""
    anchors: set[str] = set()
    generated: set[str] = set()
    previous = ""
    previous_no = 0
    class AnchorParser(HTMLParser):
        def handle_starttag(self, tag, attrs):
            for name, value in attrs:
                if name in {"id", "name"} and value is not None:
                    anchors.add(value)

    prose = dict(_markdown_prose_lines(text))
    parser = AnchorParser(convert_charrefs=True)
    parser.feed("\n".join(prose.values()))
    for line_no, line in _markdown_prose_lines(text, preserve_inline=True):
        line = re.sub(r"^(?: {0,3}>[ \t]?)+", "", line)
        heading = re.match(r"^ {0,3}#{1,6}(?:[ \t]+(.*?)|[ \t]*)$", line)
        title = None
        if heading:
            title = re.sub(r"[ \t]+#+[ \t]*$", "", heading.group(1) or "")
        elif (previous.strip() and previous_no == line_no - 1
              and not re.match(r"^(?: {4}|\t| {0,3}(?:#{1,6}(?:\s|$)|[-+*]\s|\d+[.)]\s|<|(?:=+|-+)\s*$))", previous)
              and re.fullmatch(r" {0,3}(?:=+|-+)[ \t]*", line)):
            title = previous.strip()
        if title is not None:
            # Code spans contribute literal text, never emphasis or HTML syntax.
            code_text: list[str] = []
            def preserve_code(match: re.Match[str]) -> str:
                code_text.append(match.group(2))
                return f"\x00{len(code_text) - 1}\x00"
            title = re.sub(r"(`+)(.+?)\1", preserve_code, title)
            title = re.sub(r"!?\[([^\]]*)\]\([^)]*\)", r"\1", title)
            title = html.unescape(re.sub(r"<[^>]*>", "", title))
            title = re.sub(r"(\*\*|~~|\*)(.+?)\1", r"\2", title)
            title = re.sub(r"(?<!\w)(__|_)(.+?)\1(?!\w)", r"\2", title)
            for index, literal in enumerate(code_text):
                title = title.replace(f"\x00{index}\x00", literal)
            title = title.lower()
            slug = "".join(c for c in title if c in " -_" or unicodedata.category(c)[0] in "LNM")
            slug = slug.replace(" ", "-")
            anchor, suffix = slug, 0
            while anchor in generated:
                suffix += 1
                anchor = f"{slug}-{suffix}"
            generated.add(anchor)
            anchors.add(anchor)
        previous, previous_no = line, line_no
    return anchors

def _markdown_link_findings(
    repo_root: Path,
    exclude_patterns: Iterable[str] = (),
    historical_patterns: Iterable[str] = (),
) -> list[dict[str, Any]]:
    findings: list[dict[str, Any]] = []
    link_re = re.compile(r"!?\[[^\]]*\]\(([^)]+)\)")
    scheme_re = re.compile(r"^[A-Za-z][A-Za-z0-9+.-]*:")
    historical_patterns = tuple(historical_patterns)
    for rel in _relative_files(repo_root, exclude_patterns):
        if not rel.endswith(".md"):
            continue
        path = repo_root / rel
        try:
            text = path.read_text(encoding="utf-8")
        except OSError:
            continue
        # Migrations preserve historical bodies, so their stale links are reported without blocking.
        if any(_matches(rel, pattern) for pattern in historical_patterns):
            severity, extra = "warning", {"tier": "historical"}
        else:
            severity, extra = "error", {}
        for line_no, line in _markdown_prose_lines(text):
            for raw in link_re.findall(line):
                target = raw.strip()
                if target.startswith("<") and ">" in target:
                    target = target[1:target.index(">")]
                elif target:
                    target = target.split(maxsplit=1)[0]
                if not target or target.startswith("/") or scheme_re.match(target):
                    continue
                target, separator, fragment = target.partition("#")
                target = unquote(target.split("?", 1)[0])
                resolved = (path.parent / target).resolve() if target else path.resolve()
                try:
                    resolved.relative_to(repo_root)
                except ValueError:
                    findings.append(_finding(
                        "markdown-link-outside",
                        severity,
                        rel,
                        f"Line {line_no} links outside the repository: {raw}",
                        line=line_no,
                        **extra,
                    ))
                    continue
                if not resolved.exists():
                    findings.append(_finding(
                        "markdown-link-broken",
                        severity,
                        rel,
                        f"Line {line_no} links to a missing local target: {raw}",
                        line=line_no,
                        **extra,
                    ))
                elif separator and fragment and resolved.is_file() and resolved.suffix.lower() == ".md":
                    if unquote(fragment) not in _markdown_anchors(resolved.read_text(encoding="utf-8")):
                        findings.append(_finding(
                            "markdown-fragment-broken", severity, rel,
                            f"Line {line_no} links to a missing Markdown fragment: {raw}",
                            line=line_no, **extra,
                        ))
    return findings

def _agent_note_findings(root: Path, config: dict[str, Any]) -> list[dict[str, Any]]:
    findings: list[dict[str, Any]] = []
    notes_config = config.get("agent_notes") or {}
    note_root_rel = str(notes_config.get("root") or ".agents/notes")
    note_root = root / note_root_rel
    statuses = notes_config.get("statuses") or {
        "proposed": "proposed",
        "implemented": "implemented",
        "rejected": "rejected",
        "archived": "implemented",
    }
    required = {
        "proposed": {"Problem", "Proposal", "Alternatives considered", "Acceptance criteria", "Risks"},
        "implemented": {"Problem", "Decision", "Alternatives considered", "Consequences"},
        "rejected": {"Problem", "Proposal", "Alternatives considered"},
        "archived": {"Problem", "Decision", "Alternatives considered", "Consequences"},
    }
    forbidden_implemented = {"Proposal", "Plan", "Migration plan", "Acceptance criteria"}

    if not note_root.exists():
        return findings

    for lifecycle, expected_status in statuses.items():
        lifecycle_root = note_root / lifecycle
        if not lifecycle_root.exists():
            continue
        for path in sorted(lifecycle_root.rglob("*.md")):
            if path.name in {"README.md", "_template.md"} or path.name.endswith(".zh.md"):
                continue
            rel = path.relative_to(root).as_posix()
            text = path.read_text(encoding="utf-8")
            status_match = re.search(r"(?m)^Status:\s*(.+?)\s*$", text)
            actual = status_match.group(1) if status_match else ""
            status_ok = actual == expected_status
            if lifecycle == "rejected":
                status_ok = actual == "rejected" or actual.startswith("rejected —") or actual.startswith("rejected -")
            if not status_ok:
                findings.append(_finding(
                    "agent-note-status-mismatch",
                    "error",
                    rel,
                    f"Folder {lifecycle!r} requires Status: {expected_status!r}; found {actual!r}.",
                ))

            headings = set(re.findall(r"(?m)^##\s+(.+?)\s*$", text))
            for heading in sorted(required.get(lifecycle, set()) - headings):
                findings.append(_finding(
                    "agent-note-required-heading-missing",
                    "error",
                    rel,
                    f"Agent Note in {lifecycle}/ is missing required heading: ## {heading}",
                ))
            if lifecycle in {"implemented", "archived"}:
                for heading in sorted(headings & forbidden_implemented):
                    findings.append(_finding(
                        "agent-note-forbidden-heading",
                        "error",
                        rel,
                        f"Implemented Agent Notes may not contain proposal-stage heading: ## {heading}",
                    ))
    return findings

def _budget_findings(root: Path, config: dict[str, Any]) -> list[dict[str, Any]]:
    findings: list[dict[str, Any]] = []
    for rel, rule in (config.get("budgets") or {}).items():
        path = root / rel
        if not path.is_file():
            continue
        metric = (rule or {}).get("metric", "unicode_chars")
        maximum = (rule or {}).get("max")
        if metric != "unicode_chars" or not isinstance(maximum, int):
            findings.append(_finding(
                "document-budget-invalid",
                "error",
                rel,
                "Budgets must use metric 'unicode_chars' and an integer max.",
            ))
            continue
        count = len(path.read_text(encoding="utf-8"))
        if count > maximum:
            findings.append(_finding(
                "document-budget-exceeded",
                "error",
                rel,
                f"Document has {count} Unicode characters; maximum is {maximum}.",
                actual=count,
                maximum=maximum,
            ))
    return findings

def verify_repository(repo: str | os.PathLike[str] | Path, *, completion: bool = False) -> dict[str, Any]:
    root = _normalize_repo(repo)
    config, findings = _load_governance(root)
    if config is None:
        return {"ok": False, "findings": findings, "summary": {"errors": len(findings), "warnings": 0}}

    for name, rel in (config.get("authority") or {}).items():
        if rel is None:
            continue
        path = root / str(rel)
        if not path.exists():
            findings.append(_finding(
                "authority-missing",
                "error",
                str(rel),
                f"Authority {name!r} points to a missing path.",
                authority=name,
            ))

    exclude_patterns = list(config.get("exclude") or [])
    files = _relative_files(root, exclude_patterns)
    current_patterns = list((config.get("tiers") or {}).get("current") or [])
    historical_patterns = list((config.get("tiers") or {}).get("historical") or [])
    overlap = sorted(
        rel
        for rel in files
        if any(_matches(rel, p) for p in current_patterns)
        and any(_matches(rel, p) for p in historical_patterns)
    )
    for rel in overlap:
        findings.append(_finding(
            "tier-overlap",
            "error",
            rel,
            "A file may not belong to both current and historical tiers.",
        ))

    for rel in files:
        if (rel.startswith("docs/") and rel.endswith(".md")
                and not any(_matches(rel, p) for p in current_patterns + historical_patterns)):
            findings.append(_finding(
                "documentation-untiered",
                "warning",
                rel,
                "Neither tiers.current nor tiers.historical covers this document, so authority checks skip it; "
                "move it to the tier docs/AGENTS.md assigns, or add its pattern to docs/governance.yaml.",
            ))

    findings.extend(_markdown_link_findings(root, exclude_patterns, historical_patterns))
    findings.extend(_agent_note_findings(root, config))
    findings.extend(_budget_findings(root, config))
    findings.extend(_readiness_findings(root, config, completion))
    findings.sort(key=lambda item: (item["severity"], item["code"], item["path"], item["message"]))
    errors = sum(1 for finding in findings if finding["severity"] == "error")
    warnings = sum(1 for finding in findings if finding["severity"] != "error")
    return {"ok": errors == 0, "findings": findings, "summary": {"errors": errors, "warnings": warnings}}

def _current_markdown_files(root: Path, config: dict[str, Any]) -> list[Path]:
    patterns = list((config.get("tiers") or {}).get("current") or [])
    exclude_patterns = list(config.get("exclude") or [])
    return [
        root / rel
        for rel in _relative_files(root, exclude_patterns)
        if rel.endswith(".md") and any(_matches(rel, pattern) for pattern in patterns)
    ]

def audit_repository(repo: str | os.PathLike[str] | Path) -> dict[str, Any]:
    root = _normalize_repo(repo)
    verified = verify_repository(root)
    findings = list(verified["findings"])
    config, config_findings = _load_governance(root)
    if config is None:
        return verified
    findings.extend(config_findings)

    audit = config.get("audit") or {}
    minimum = int(audit.get("duplicate_min_chars", 180))
    occurrences: dict[str, list[str]] = {}
    for path in _current_markdown_files(root, config):
        rel = path.relative_to(root).as_posix()
        text = path.read_text(encoding="utf-8")
        for paragraph in re.split(r"\n\s*\n", text):
            normalized = " ".join(paragraph.split())
            if len(normalized) < minimum or normalized.startswith("#") or normalized.startswith("```"):
                continue
            occurrences.setdefault(normalized, []).append(rel)
    for paragraph, paths in sorted(occurrences.items()):
        unique_paths = sorted(set(paths))
        if len(unique_paths) > 1:
            findings.append(_finding(
                "duplicate-prose",
                "warning",
                unique_paths[0],
                "A long prose block is duplicated across current documentation owners.",
                paths=unique_paths,
                excerpt=paragraph[:160],
            ))

    historical_patterns = list((config.get("tiers") or {}).get("historical") or [])
    historical_prefixes = sorted({pattern[:-3].rstrip("/") if pattern.endswith("/**") else pattern for pattern in historical_patterns})
    terms = [str(term).lower() for term in audit.get("historical_authority_terms", [])]
    for path in _current_markdown_files(root, config):
        rel = path.relative_to(root).as_posix()
        for line_no, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
            lowered = line.lower()
            if terms and any(term in lowered for term in terms) and any(prefix in line for prefix in historical_prefixes):
                findings.append(_finding(
                    "historical-authority-leak",
                    "warning",
                    rel,
                    f"Line {line_no} names a historical tier as current authority.",
                    line=line_no,
                ))

    findings.sort(key=lambda item: (item["severity"], item["code"], item["path"], item["message"]))
    errors = sum(1 for finding in findings if finding["severity"] == "error")
    warnings = sum(1 for finding in findings if finding["severity"] != "error")
    return {"ok": errors == 0, "findings": findings, "summary": {"errors": errors, "warnings": warnings}}

def _require_git_root(root: Path) -> None:
    result = subprocess.run(["git", "-C", str(root), "rev-parse", "--show-toplevel"],
                            text=True, capture_output=True)
    if result.returncode or Path(result.stdout.strip()).resolve() != root:
        raise ValueError("impact requires a Git worktree root for --repo and --code-repo")

def _committed_changes(root: Path, base: str, head: str) -> list[str]:
    # Resolve refs first: option-looking input cannot become a diff flag.
    refs = [subprocess.run(["git", "-C", str(root), "rev-parse", "--verify", "--end-of-options", ref + "^{commit}"],
                          check=True, text=True, capture_output=True).stdout.strip() for ref in (base, head)]
    result = subprocess.run(["git", "-C", str(root), "diff", "--name-only", "-z", f"{refs[0]}...{refs[1]}", "--"],
                            check=True, text=True, capture_output=True)
    return sorted(path for path in result.stdout.split("\0") if path)

def impact_repository(
    repo: str | os.PathLike[str] | Path,
    *,
    base: str,
    head: str = "HEAD",
    code_repo: str | os.PathLike[str] | Path | None = None,
    code_base: str | None = None,
    code_head: str | None = None,
) -> dict[str, Any]:
    root = _normalize_repo(repo)
    _require_git_root(root)
    config, findings = _load_governance(root)
    if config is None:
        return {"ok": False, "changed_files": [], "findings": findings}
    external = any(m.get("code_repository", "local") == "external" for m in config["impact_mappings"])
    if external or code_repo is not None or code_base is not None or code_head is not None:
        if not code_repo or not code_base:
            raise ValueError("external impact requires both --code-repo and --code-base; --code-head defaults to HEAD")
    code_root = _normalize_repo(code_repo) if code_repo else None
    if code_root:
        _require_git_root(code_root)
        if code_root == root:
            raise ValueError("--code-repo must be an independent repository root")
    try:
        changed = _committed_changes(root, base, head)
        code_changed_files = _committed_changes(code_root, code_base, code_head or "HEAD") if code_root else []
    except (OSError, subprocess.CalledProcessError) as exc:
        message = exc.stderr.strip() if isinstance(exc, subprocess.CalledProcessError) and exc.stderr else str(exc)
        findings.append(_finding("git-diff-failed", "error", ".", f"Unable to compute Git diff: {message}"))
        return {"ok": False, "changed_files": [], "findings": findings}

    existing = _relative_files(root, config.get("exclude") or [])
    for mapping in config.get("impact_mappings") or []:
        code_patterns = list(mapping.get("code") or [])
        doc_patterns = list(mapping.get("docs") or [])
        source_changes = code_changed_files if mapping.get("code_repository", "local") == "external" else changed
        code_changed = sorted(path for path in source_changes if any(_matches(path, pattern) for pattern in code_patterns))
        if not code_changed:
            continue
        docs_changed = sorted(path for path in changed if any(_matches(path, pattern) for pattern in doc_patterns))
        if docs_changed:
            continue
        if not any(_matches(path, pattern) for path in existing for pattern in doc_patterns):
            # A growing project reaches the mapped code before it has the owner; ask for the owner, never block on it.
            findings.append(_finding(
                "doc-owner-missing",
                "warning",
                str(mapping.get("name") or "unnamed-mapping"),
                "Mapped code changed and no owning document exists yet; create the tier docs/AGENTS.md assigns, "
                "or narrow the mapping.",
                changed_code=code_changed,
                expected_docs=doc_patterns,
            ))
            continue
        level = str(mapping.get("level") or "soft")
        severity = "error" if level == "hard" else "warning"
        code = "hard-doc-impact-missing" if level == "hard" else "soft-doc-impact-unreviewed"
        findings.append(_finding(
            code,
            severity,
            str(mapping.get("name") or "unnamed-mapping"),
            "Mapped code changed without any owning documentation changing.",
            changed_code=code_changed,
            expected_docs=doc_patterns,
        ))

    findings.sort(key=lambda item: (item["severity"], item["code"], item["path"], item["message"]))
    return {
        "ok": not any(finding["severity"] == "error" for finding in findings),
        "changed_files": changed,
        "changed_code_files": code_changed_files,
        "findings": findings,
    }

def _emit(payload: dict[str, Any], as_json: bool) -> None:
    if as_json:
        print(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True))
        return
    for key, value in payload.items():
        if isinstance(value, list):
            print(f"{key}:")
            for item in value:
                print(f"  - {item}")
        else:
            print(f"{key}: {value}")


def main(argv=None):
    parser = argparse.ArgumentParser(description="Repository-local documentation checks")
    parser.add_argument("--repo", default=".")
    parser.add_argument("--base")
    parser.add_argument("--head")
    parser.add_argument("--code-repo")
    parser.add_argument("--code-base")
    parser.add_argument("--code-head")
    parser.add_argument("--completion", action="store_true", help="reject incomplete scaffold; semantic review is still required")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args(argv)
    try:
        if not args.base and any(v is not None for v in (args.head, args.code_repo, args.code_base, args.code_head)):
            raise ValueError("--head and --code-* require --base for impact checking")
        payload = audit_repository(args.repo)
        if args.completion:
            completion = verify_repository(args.repo, completion=True)
            payload["findings"] = completion["findings"] + [f for f in payload["findings"] if f["code"] in {"duplicate-prose", "historical-authority-leak"}]
        if args.base:
            impact = impact_repository(args.repo, base=args.base, head=args.head or "HEAD",
                                       code_repo=args.code_repo, code_base=args.code_base, code_head=args.code_head)
            payload["changed_files"] = impact.get("changed_files", [])
            payload["changed_code_files"] = impact.get("changed_code_files", [])
            payload["findings"].extend(impact["findings"])
        payload["ok"] = not any(f["severity"] == "error" for f in payload["findings"])
        payload["summary"] = {"errors": sum(f["severity"] == "error" for f in payload["findings"]),
                              "warnings": sum(f["severity"] != "error" for f in payload["findings"])}
        payload["assurance"] = STRUCTURE_ONLY_ASSURANCE
        _emit(payload, args.json)
        return 0 if payload["ok"] else 1
    except (ValueError, OSError) as exc:
        _emit({"ok": False, "error": str(exc)}, args.json)
        return 2

if __name__ == "__main__":
    raise SystemExit(main())
