#!/usr/bin/env python3
"""Emit the standalone verifier from the actual CLI check functions; --check is read-only."""
from __future__ import annotations
import argparse
import ast
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'dsh-doc-audits/scripts/repo_docs.py'
FUNCTIONS = {
    '_normalize_repo', '_relative_files', '_matches', '_finding', '_manifest_issues',
    '_readiness_findings', '_load_governance', '_markdown_link_findings',
    '_agent_note_findings', '_budget_findings', 'verify_repository',
    '_current_markdown_files', 'audit_repository', 'impact_repository', '_emit',
}
WRAPPER = '''
def main(argv=None):
    parser = argparse.ArgumentParser(description="Repository-local documentation checks")
    parser.add_argument("--repo", default=".")
    parser.add_argument("--base")
    parser.add_argument("--completion", action="store_true", help="reject incomplete scaffold; semantic review is still required")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args(argv)
    try:
        payload = audit_repository(args.repo)
        if args.completion:
            completion = verify_repository(args.repo, completion=True)
            payload["findings"] = completion["findings"] + [f for f in payload["findings"] if f["code"] in {"duplicate-prose", "historical-authority-leak"}]
        if args.base:
            impact = impact_repository(args.repo, base=args.base)
            payload["changed_files"] = impact.get("changed_files", [])
            payload["findings"].extend(impact["findings"])
        payload["ok"] = not any(f["severity"] == "error" for f in payload["findings"])
        payload["summary"] = {"errors": sum(f["severity"] == "error" for f in payload["findings"]),
                              "warnings": sum(f["severity"] != "error" for f in payload["findings"])}
        payload["assurance"] = "deterministic checks only; semantic review and fresh-session assessment remain agent tasks"
        _emit(payload, args.json)
        return 0 if payload["ok"] else 1
    except (ValueError, OSError) as exc:
        _emit({"ok": False, "error": str(exc)}, args.json)
        return 2

if __name__ == "__main__":
    raise SystemExit(main())
'''

def render():
    text = SOURCE.read_text(encoding='utf-8')
    nodes = ast.parse(text).body
    selected = []
    for node in nodes:
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            selected.append(ast.get_source_segment(text, node))
        elif isinstance(node, ast.Assign) and any(isinstance(t, ast.Name) and t.id == 'DEFAULT_EXCLUDE_PATTERNS' for t in node.targets):
            selected.append(ast.get_source_segment(text, node))
        elif isinstance(node, ast.FunctionDef) and node.name in FUNCTIONS:
            selected.append(ast.get_source_segment(text, node))
    header = '#!/usr/bin/env python3\n"""Generated by dsh-doc-audits {{SKILL_VERSION}}; do not edit directly.\nSource: dsh-doc-audits/scripts/repo_docs.py; generator: scripts/generate_verifier.py.\n"""\n'
    version = next(ast.literal_eval(n.value) for n in nodes if isinstance(n, ast.Assign) and any(isinstance(t, ast.Name) and t.id == 'VERSION' for t in n.targets))
    asset = header + '\n\n'.join(selected) + '\n\n' + WRAPPER
    return asset, asset.replace('{{SKILL_VERSION}}', version)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    contents = render()
    targets = [ROOT/'dsh-doc-audits/assets/repo-governance/scripts/verify_docs.py', ROOT/'scripts/verify_docs.py']
    for target, content in zip(targets, contents):
        if args.check:
            if not target.exists() or target.read_text(encoding='utf-8') != content:
                raise SystemExit(f'stale generated verifier: {target.relative_to(ROOT)}')
        else:
            target.write_text(content, encoding='utf-8')
    print('verifier-generation: PASS')

if __name__ == '__main__':
    main()
