#!/usr/bin/env python3
"""Regenerate vendored third-party skills from a pinned upstream plus local patches.

Each vendor lives in vendor/<name>/sync.json. Patches are exact text replacements;
a patch whose text is missing, or a forbidden string left after patching, aborts
the run before any skill directory or pin is touched.
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


class SyncError(Exception):
    pass


def git(*args: str, cwd: Path | None = None) -> str:
    result = subprocess.run(["git", *args], cwd=cwd, check=True, text=True, capture_output=True)
    return result.stdout.strip()


def load(root: Path, name: str) -> dict:
    path = root / "vendor" / name / "sync.json"
    if not path.is_file():
        raise SyncError(f"no vendor config: {path.relative_to(root)}")
    return json.loads(path.read_text(encoding="utf-8"))


def fetch(cfg: dict, ref: str, workdir: Path) -> tuple[Path, str]:
    git("init", "-q", str(workdir))
    git("remote", "add", "origin", cfg["repo"], cwd=workdir)
    git("fetch", "-q", "--depth", "1", "--filter=blob:none", "origin", ref, cwd=workdir)
    git("sparse-checkout", "set", "--no-cone", cfg["license"], *cfg["skills"].values(), cwd=workdir)
    git("checkout", "-q", "FETCH_HEAD", cwd=workdir)
    return workdir, git("rev-parse", "FETCH_HEAD", cwd=workdir)


def build(cfg: dict, source: Path, sha: str, stage: Path) -> None:
    license_text = (source / cfg["license"]).read_text(encoding="utf-8")
    for skill, upstream in cfg["skills"].items():
        src = source / upstream
        if not (src / "SKILL.md").is_file():
            raise SyncError(f"upstream has no {upstream}/SKILL.md")
        shutil.copytree(src, stage / skill)
        (stage / skill / "LICENSE").write_text(license_text, encoding="utf-8")
    for patch in cfg["patches"]:
        path = stage / patch["file"]
        text = path.read_text(encoding="utf-8")
        if patch["old"] not in text:
            raise SyncError(f"patch no longer applies to {patch['file']}: {patch['old']!r}")
        path.write_text(text.replace(patch["old"], patch["new"]), encoding="utf-8")
    marker = f"# Generated by scripts/sync_vendor.py from {cfg['repo']}@{sha[:12]}; edit vendor/*/sync.json, not this file.\n"
    for skill in cfg["skills"]:
        for path in sorted((stage / skill).rglob("*.md")):
            text = path.read_text(encoding="utf-8")
            for bad in cfg.get("forbid", []):
                if bad in text:
                    raise SyncError(f"{path.relative_to(stage)} still contains {bad!r} after patching")
        skill_md = stage / skill / "SKILL.md"
        text = skill_md.read_text(encoding="utf-8")
        if not text.startswith("---\n"):
            raise SyncError(f"{skill}/SKILL.md has no frontmatter")
        skill_md.write_text("---\n" + marker + text[4:], encoding="utf-8")


def update(root: Path, name: str, ref: str, source: Path | None) -> str:
    cfg = load(root, name)
    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        if source is None:
            source, sha = fetch(cfg, ref, tmp_path / "upstream")
        else:
            sha = ref
        stage = tmp_path / "stage"
        stage.mkdir()
        build(cfg, source, sha, stage)
        for skill in cfg["skills"]:
            dest = root / skill
            if dest.exists():
                shutil.rmtree(dest)
            shutil.copytree(stage / skill, dest)
    cfg["pinned"] = sha
    (root / "vendor" / name / "sync.json").write_text(json.dumps(cfg, indent=2) + "\n", encoding="utf-8")
    return sha


def status(root: Path, name: str) -> str:
    cfg = load(root, name)
    head = git("ls-remote", cfg["repo"], "HEAD").split()[0]
    state = "up to date" if head == cfg["pinned"] else "upstream has new commits"
    return f"{name}: pinned {cfg['pinned'][:12] or '(none)'}, upstream {head[:12]} ({state})"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT, help=argparse.SUPPRESS)
    sub = parser.add_subparsers(dest="command", required=True)
    st = sub.add_parser("status", help="compare the pinned commit with upstream HEAD")
    st.add_argument("name")
    up = sub.add_parser("update", help="fetch upstream, apply patches, rewrite the vendored skills")
    up.add_argument("name")
    up.add_argument("--ref", default="HEAD", help="upstream branch, tag or commit (default HEAD)")
    up.add_argument("--source", type=Path, help="use a local upstream checkout instead of fetching")
    args = parser.parse_args(argv)
    try:
        if args.command == "status":
            print(status(args.root, args.name))
        else:
            sha = update(args.root, args.name, args.ref, args.source)
            print(f"{args.name}: synced {sha[:12]}")
    except (SyncError, subprocess.CalledProcessError) as exc:
        detail = getattr(exc, "stderr", "") or ""
        print(f"sync_vendor: {exc} {detail}".strip(), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
