#!/usr/bin/env python3
"""Generated by dsh-doc-audits 0.2.0; do not edit directly.
Source: dsh-doc-audits/scripts/repo_docs.py; generator: scripts/generate_verifier.py.
"""
from __future__ import annotations

import argparse

import json

import os

import re

import subprocess

import sys

from fnmatch import fnmatchcase

from urllib.parse import unquote

from datetime import date

from pathlib import Path

from typing import Any, Iterable

DEFAULT_EXCLUDE_PATTERNS = (
    ".git/**",
    ".dsh-doc-audits/**",
    ".venv/**",
    "node_modules/**",
    "**/__pycache__/**",
)

def _normalize_repo(repo: str | os.PathLike[str] | Path) -> Path:
    path = Path(repo).expanduser().resolve()
    if not path.exists():
        raise FileNotFoundError(f"repository path does not exist: {path}")
    if not path.is_dir():
        raise NotADirectoryError(f"repository path is not a directory: {path}")
    return path

def _relative_files(repo: Path, exclude_patterns: Iterable[str] = ()) -> list[str]:
    patterns = (*DEFAULT_EXCLUDE_PATTERNS, *(str(pattern) for pattern in exclude_patterns))
    files: list[str] = []
    for path in repo.rglob("*"):
        if not path.is_file():
            continue
        try:
            rel = path.relative_to(repo).as_posix()
        except ValueError:
            continue
        if any(_matches(rel, pattern) for pattern in patterns):
            continue
        files.append(rel)
    return sorted(files)

def _finding(code: str, severity: str, path: str, message: str, **extra: Any) -> dict[str, Any]:
    value: dict[str, Any] = {
        "code": code,
        "severity": severity,
        "path": path,
        "message": message,
    }
    value.update(extra)
    return value

def _matches(path: str, pattern: str) -> bool:
    normalized = path.replace(os.sep, "/").lstrip("./")
    pattern = pattern.replace(os.sep, "/").lstrip("./")
    if pattern.endswith("/**"):
        prefix = pattern[:-3].rstrip("/")
        return normalized == prefix or normalized.startswith(prefix + "/")
    return fnmatchcase(normalized, pattern)

def _manifest_issues(data: Any) -> list[str]:
    """Validate the public manifest contract, including nested types, before use."""
    issues: list[str] = []
    if not isinstance(data, dict):
        return ["root must be an object"]
    required = {"schema_version", "authority", "tiers", "agent_notes", "budgets", "impact_mappings", "audit"}
    issues.extend(f"missing field: {name}" for name in sorted(required - data.keys()))
    if data.get("schema_version") != 1 or isinstance(data.get("schema_version"), bool):
        issues.append("schema_version must be 1")
    def strings(value: Any) -> bool:
        return isinstance(value, list) and all(isinstance(x, str) and bool(x.strip()) for x in value)
    def relative(value: Any, pattern: bool = False) -> bool:
        return (isinstance(value, str) and bool(value) and not value.startswith(("/", "~"))
                and "\\" not in value and ":" not in value and ".." not in value.split("/")
                and not any(ord(c) < 32 for c in value)
                and (pattern or not any(c in value for c in "*?[]")))
    authority = data.get("authority")
    if not isinstance(authority, dict) or not authority or not all(relative(v) for v in authority.values()):
        issues.append("authority must be a nonempty map of names to relative file paths")
    tiers = data.get("tiers")
    if not isinstance(tiers, dict) or not strings(tiers.get("current")) or not strings(tiers.get("historical")):
        issues.append("tiers must contain current and historical string arrays")
    elif any(not strings(arr) for arr in tiers.values()) or not tiers["current"] or not all(relative(v, True) for arr in tiers.values() for v in arr):
        issues.append("tiers require relative patterns and a nonempty current tier")
    notes = data.get("agent_notes")
    expected = {"proposed": "proposed", "implemented": "implemented", "rejected": "rejected", "archived": "implemented"}
    if not isinstance(notes, dict) or not relative(notes.get("root")) or notes.get("statuses") != expected:
        issues.append("agent_notes requires a relative root and the four lifecycle/status pairs")
    budgets = data.get("budgets")
    if not isinstance(budgets, dict):
        issues.append("budgets must be an object")
    else:
        for path, rule in budgets.items():
            if (not relative(path) or not isinstance(rule, dict) or rule.get("metric") != "unicode_chars"
                    or type(rule.get("max")) is not int or rule["max"] < 1):
                issues.append(f"invalid budget: {path}")
    mappings = data.get("impact_mappings")
    if not isinstance(mappings, list):
        issues.append("impact_mappings must be an array")
    else:
        names = set()
        for item in mappings:
            if (not isinstance(item, dict) or not isinstance(item.get("name"), str) or not item["name"]
                    or not strings(item.get("code")) or not item["code"]
                    or not strings(item.get("docs")) or not item["docs"]
                    or item.get("level") not in {"hard", "soft"}):
                issues.append("each impact mapping requires name, code, docs and hard/soft level")
            elif item["name"] in names or not all(relative(v, True) for v in item["code"] + item["docs"]):
                issues.append("impact mappings require unique names and relative patterns")
            else:
                names.add(item["name"])
    audit = data.get("audit")
    if (not isinstance(audit, dict) or type(audit.get("duplicate_min_chars")) is not int
            or audit["duplicate_min_chars"] < 1 or not strings(audit.get("historical_authority_terms"))):
        issues.append("audit requires a positive duplicate_min_chars and historical_authority_terms array")
    if "exclude" in data and (not strings(data["exclude"]) or not all(relative(v, True) for v in data["exclude"])):
        issues.append("exclude must contain relative patterns")
    return issues

def _readiness_findings(root: Path, config: dict[str, Any], completion: bool = False) -> list[dict[str, Any]]:
    """Scaffolding is allowed during bootstrap; never certify it as migrated."""
    findings: list[dict[str, Any]] = []
    prompts = re.compile(r"^(?:TODO|TBD|FIXME)(?:\b|[:：])|^\{\{[^}]+\}\}|"
                         r"^(?:Describe|Record|Summarize|Name|State|Link|Document|List)\b.*(?:here\b|owning path|dependency order|a maintainer must|durable stores|capabilities may|environments and deployment)", re.I)
    authority_paths = set(config.get("authority", {}).values())
    for path in _current_markdown_files(root, config):
        if path.name == "_template.md":
            continue
        rel = path.relative_to(root).as_posix()
        text = path.read_text(encoding="utf-8")
        scaffold = re.search(r"(?mi)^Status:\s*scaffold\s*$", text) is not None
        if scaffold:
            findings.append(_finding("documentation-scaffold", "error" if completion else "warning", rel,
                                     "Scaffold is not current authority; semantic authoring is pending."))
            continue
        fenced = False
        prose = []
        for line_no, line in enumerate(text.splitlines(), 1):
            stripped = line.strip()
            if stripped.startswith(("```", "~~~")):
                fenced = not fenced
                continue
            if fenced or not stripped or stripped.startswith(("#", ">", "<!--", "Status:", "Last reviewed:", "Owner paths:")):
                continue
            prose.append(stripped)
            if prompts.search(re.sub(r"^(?:[-*+] |[0-9]+[.)] )", "", stripped)):
                findings.append(_finding("current-authority-placeholder", "error", rel,
                                         "Current documentation contains an unfinished authoring prompt.", line=line_no))
        if completion and (rel in authority_paths or re.search(r"(?mi)^Status:\s*current authority", text)) and not prose:
            findings.append(_finding("current-authority-empty", "error", rel, "Current owner has no substantive content."))
    return findings

def _load_governance(root: Path) -> tuple[dict[str, Any] | None, list[dict[str, Any]]]:
    path = root / "docs" / "governance.yaml"
    if not path.is_file():
        return None, [_finding(
            "governance-missing",
            "error",
            "docs/governance.yaml",
            "The repository has no governance manifest.",
        )]
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        return None, [_finding(
            "governance-invalid",
            "error",
            "docs/governance.yaml",
            f"The governance manifest must be JSON-compatible YAML: {exc}",
        )]
    if not isinstance(data, dict):
        return None, [_finding(
            "governance-invalid",
            "error",
            "docs/governance.yaml",
            "The governance manifest root must be an object.",
        )]
    issues = _manifest_issues(data)
    if issues:
        return None, [_finding("governance-invalid", "error", "docs/governance.yaml", issue) for issue in issues]
    return data, []

def _markdown_link_findings(
    root: Path,
    exclude_patterns: Iterable[str] = (),
) -> list[dict[str, Any]]:
    findings: list[dict[str, Any]] = []
    link_re = re.compile(r"!?\[[^\]]*\]\(([^)]+)\)")
    scheme_re = re.compile(r"^[A-Za-z][A-Za-z0-9+.-]*:")
    for rel in _relative_files(root, exclude_patterns):
        if not rel.endswith(".md"):
            continue
        path = root / rel
        try:
            text = path.read_text(encoding="utf-8")
        except OSError:
            continue
        for line_no, line in enumerate(text.splitlines(), start=1):
            for raw in link_re.findall(line):
                target = raw.strip()
                if target.startswith("<") and ">" in target:
                    target = target[1:target.index(">")]
                else:
                    target = target.split(maxsplit=1)[0]
                if not target or target.startswith("#") or target.startswith("/") or scheme_re.match(target):
                    continue
                target = unquote(target.split("#", 1)[0].split("?", 1)[0])
                if not target:
                    continue
                resolved = (path.parent / target).resolve()
                try:
                    resolved.relative_to(root)
                except ValueError:
                    findings.append(_finding(
                        "markdown-link-outside",
                        "error",
                        rel,
                        f"Line {line_no} links outside the repository: {raw}",
                        line=line_no,
                    ))
                    continue
                if not resolved.exists():
                    findings.append(_finding(
                        "markdown-link-broken",
                        "error",
                        rel,
                        f"Line {line_no} links to a missing local target: {raw}",
                        line=line_no,
                    ))
    return findings

def _agent_note_findings(root: Path, config: dict[str, Any]) -> list[dict[str, Any]]:
    findings: list[dict[str, Any]] = []
    notes_config = config.get("agent_notes") or {}
    note_root_rel = str(notes_config.get("root") or ".agents/notes")
    note_root = root / note_root_rel
    statuses = notes_config.get("statuses") or {
        "proposed": "proposed",
        "implemented": "implemented",
        "rejected": "rejected",
        "archived": "implemented",
    }
    required = {
        "proposed": {"Problem", "Proposal", "Alternatives considered", "Acceptance criteria", "Risks"},
        "implemented": {"Problem", "Decision", "Alternatives considered", "Consequences"},
        "rejected": {"Problem", "Proposal", "Alternatives considered"},
        "archived": {"Problem", "Decision", "Alternatives considered", "Consequences"},
    }
    forbidden_implemented = {"Proposal", "Plan", "Migration plan", "Acceptance criteria"}

    if not note_root.exists():
        return findings

    for lifecycle, expected_status in statuses.items():
        lifecycle_root = note_root / lifecycle
        if not lifecycle_root.exists():
            continue
        for path in sorted(lifecycle_root.rglob("*.md")):
            if path.name in {"README.md", "_template.md"} or path.name.endswith(".zh.md"):
                continue
            rel = path.relative_to(root).as_posix()
            text = path.read_text(encoding="utf-8")
            status_match = re.search(r"(?m)^Status:\s*(.+?)\s*$", text)
            actual = status_match.group(1) if status_match else ""
            status_ok = actual == expected_status
            if lifecycle == "rejected":
                status_ok = actual == "rejected" or actual.startswith("rejected —") or actual.startswith("rejected -")
            if not status_ok:
                findings.append(_finding(
                    "agent-note-status-mismatch",
                    "error",
                    rel,
                    f"Folder {lifecycle!r} requires Status: {expected_status!r}; found {actual!r}.",
                ))

            headings = set(re.findall(r"(?m)^##\s+(.+?)\s*$", text))
            for heading in sorted(required.get(lifecycle, set()) - headings):
                findings.append(_finding(
                    "agent-note-required-heading-missing",
                    "error",
                    rel,
                    f"Agent Note in {lifecycle}/ is missing required heading: ## {heading}",
                ))
            if lifecycle in {"implemented", "archived"}:
                for heading in sorted(headings & forbidden_implemented):
                    findings.append(_finding(
                        "agent-note-forbidden-heading",
                        "error",
                        rel,
                        f"Implemented Agent Notes may not contain proposal-stage heading: ## {heading}",
                    ))
    return findings

def _budget_findings(root: Path, config: dict[str, Any]) -> list[dict[str, Any]]:
    findings: list[dict[str, Any]] = []
    for rel, rule in (config.get("budgets") or {}).items():
        path = root / rel
        if not path.is_file():
            continue
        metric = (rule or {}).get("metric", "unicode_chars")
        maximum = (rule or {}).get("max")
        if metric != "unicode_chars" or not isinstance(maximum, int):
            findings.append(_finding(
                "document-budget-invalid",
                "error",
                rel,
                "Budgets must use metric 'unicode_chars' and an integer max.",
            ))
            continue
        count = len(path.read_text(encoding="utf-8"))
        if count > maximum:
            findings.append(_finding(
                "document-budget-exceeded",
                "error",
                rel,
                f"Document has {count} Unicode characters; maximum is {maximum}.",
                actual=count,
                maximum=maximum,
            ))
    return findings

def verify_repository(repo: str | os.PathLike[str] | Path, *, completion: bool = False) -> dict[str, Any]:
    root = _normalize_repo(repo)
    config, findings = _load_governance(root)
    if config is None:
        return {"ok": False, "findings": findings, "summary": {"errors": len(findings), "warnings": 0}}

    for name, rel in (config.get("authority") or {}).items():
        if rel is None:
            continue
        path = root / str(rel)
        if not path.exists():
            findings.append(_finding(
                "authority-missing",
                "error",
                str(rel),
                f"Authority {name!r} points to a missing path.",
                authority=name,
            ))

    exclude_patterns = list(config.get("exclude") or [])
    files = _relative_files(root, exclude_patterns)
    current_patterns = list((config.get("tiers") or {}).get("current") or [])
    historical_patterns = list((config.get("tiers") or {}).get("historical") or [])
    overlap = sorted(
        rel
        for rel in files
        if any(_matches(rel, p) for p in current_patterns)
        and any(_matches(rel, p) for p in historical_patterns)
    )
    for rel in overlap:
        findings.append(_finding(
            "tier-overlap",
            "error",
            rel,
            "A file may not belong to both current and historical tiers.",
        ))

    findings.extend(_markdown_link_findings(root, exclude_patterns))
    findings.extend(_agent_note_findings(root, config))
    findings.extend(_budget_findings(root, config))
    findings.extend(_readiness_findings(root, config, completion))
    findings.sort(key=lambda item: (item["severity"], item["code"], item["path"], item["message"]))
    errors = sum(1 for finding in findings if finding["severity"] == "error")
    warnings = sum(1 for finding in findings if finding["severity"] != "error")
    return {"ok": errors == 0, "findings": findings, "summary": {"errors": errors, "warnings": warnings}}

def _current_markdown_files(root: Path, config: dict[str, Any]) -> list[Path]:
    patterns = list((config.get("tiers") or {}).get("current") or [])
    exclude_patterns = list(config.get("exclude") or [])
    return [
        root / rel
        for rel in _relative_files(root, exclude_patterns)
        if rel.endswith(".md") and any(_matches(rel, pattern) for pattern in patterns)
    ]

def audit_repository(repo: str | os.PathLike[str] | Path) -> dict[str, Any]:
    root = _normalize_repo(repo)
    verified = verify_repository(root)
    findings = list(verified["findings"])
    config, config_findings = _load_governance(root)
    if config is None:
        return verified
    findings.extend(config_findings)

    audit = config.get("audit") or {}
    minimum = int(audit.get("duplicate_min_chars", 180))
    occurrences: dict[str, list[str]] = {}
    for path in _current_markdown_files(root, config):
        rel = path.relative_to(root).as_posix()
        text = path.read_text(encoding="utf-8")
        for paragraph in re.split(r"\n\s*\n", text):
            normalized = " ".join(paragraph.split())
            if len(normalized) < minimum or normalized.startswith("#") or normalized.startswith("```"):
                continue
            occurrences.setdefault(normalized, []).append(rel)
    for paragraph, paths in sorted(occurrences.items()):
        unique_paths = sorted(set(paths))
        if len(unique_paths) > 1:
            findings.append(_finding(
                "duplicate-prose",
                "warning",
                unique_paths[0],
                "A long prose block is duplicated across current documentation owners.",
                paths=unique_paths,
                excerpt=paragraph[:160],
            ))

    historical_patterns = list((config.get("tiers") or {}).get("historical") or [])
    historical_prefixes = sorted({pattern[:-3].rstrip("/") if pattern.endswith("/**") else pattern for pattern in historical_patterns})
    terms = [str(term).lower() for term in audit.get("historical_authority_terms", [])]
    for path in _current_markdown_files(root, config):
        rel = path.relative_to(root).as_posix()
        for line_no, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
            lowered = line.lower()
            if terms and any(term in lowered for term in terms) and any(prefix in line for prefix in historical_prefixes):
                findings.append(_finding(
                    "historical-authority-leak",
                    "warning",
                    rel,
                    f"Line {line_no} names a historical tier as current authority.",
                    line=line_no,
                ))

    findings.sort(key=lambda item: (item["severity"], item["code"], item["path"], item["message"]))
    errors = sum(1 for finding in findings if finding["severity"] == "error")
    warnings = sum(1 for finding in findings if finding["severity"] != "error")
    return {"ok": errors == 0, "findings": findings, "summary": {"errors": errors, "warnings": warnings}}

def impact_repository(
    repo: str | os.PathLike[str] | Path,
    *,
    base: str,
    head: str = "HEAD",
) -> dict[str, Any]:
    root = _normalize_repo(repo)
    config, findings = _load_governance(root)
    if config is None:
        return {"ok": False, "changed_files": [], "findings": findings}
    try:
        completed = subprocess.run(
            ["git", "-C", str(root), "diff", "--name-only", f"{base}...{head}"],
            check=True,
            text=True,
            capture_output=True,
        )
    except (OSError, subprocess.CalledProcessError) as exc:
        message = exc.stderr.strip() if isinstance(exc, subprocess.CalledProcessError) and exc.stderr else str(exc)
        findings.append(_finding("git-diff-failed", "error", ".", f"Unable to compute Git diff: {message}"))
        return {"ok": False, "changed_files": [], "findings": findings}

    changed = sorted(line.strip().replace(os.sep, "/") for line in completed.stdout.splitlines() if line.strip())
    for mapping in config.get("impact_mappings") or []:
        code_patterns = list(mapping.get("code") or [])
        doc_patterns = list(mapping.get("docs") or [])
        code_changed = sorted(path for path in changed if any(_matches(path, pattern) for pattern in code_patterns))
        if not code_changed:
            continue
        docs_changed = sorted(path for path in changed if any(_matches(path, pattern) for pattern in doc_patterns))
        if docs_changed:
            continue
        level = str(mapping.get("level") or "soft")
        severity = "error" if level == "hard" else "warning"
        code = "hard-doc-impact-missing" if level == "hard" else "soft-doc-impact-unreviewed"
        findings.append(_finding(
            code,
            severity,
            str(mapping.get("name") or "unnamed-mapping"),
            "Mapped code changed without any owning documentation changing.",
            changed_code=code_changed,
            expected_docs=doc_patterns,
        ))

    findings.sort(key=lambda item: (item["severity"], item["code"], item["path"], item["message"]))
    return {
        "ok": not any(finding["severity"] == "error" for finding in findings),
        "changed_files": changed,
        "findings": findings,
    }

def _emit(payload: dict[str, Any], as_json: bool) -> None:
    if as_json:
        print(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True))
        return
    for key, value in payload.items():
        if isinstance(value, list):
            print(f"{key}:")
            for item in value:
                print(f"  - {item}")
        else:
            print(f"{key}: {value}")


def main(argv=None):
    parser = argparse.ArgumentParser(description="Repository-local documentation checks")
    parser.add_argument("--repo", default=".")
    parser.add_argument("--base")
    parser.add_argument("--completion", action="store_true", help="reject incomplete scaffold; semantic review is still required")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args(argv)
    try:
        payload = audit_repository(args.repo)
        if args.completion:
            completion = verify_repository(args.repo, completion=True)
            payload["findings"] = completion["findings"] + [f for f in payload["findings"] if f["code"] in {"duplicate-prose", "historical-authority-leak"}]
        if args.base:
            impact = impact_repository(args.repo, base=args.base)
            payload["changed_files"] = impact.get("changed_files", [])
            payload["findings"].extend(impact["findings"])
        payload["ok"] = not any(f["severity"] == "error" for f in payload["findings"])
        payload["summary"] = {"errors": sum(f["severity"] == "error" for f in payload["findings"]),
                              "warnings": sum(f["severity"] != "error" for f in payload["findings"])}
        payload["assurance"] = "deterministic checks only; semantic review and fresh-session assessment remain agent tasks"
        _emit(payload, args.json)
        return 0 if payload["ok"] else 1
    except (ValueError, OSError) as exc:
        _emit({"ok": False, "error": str(exc)}, args.json)
        return 2

if __name__ == "__main__":
    raise SystemExit(main())
